version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    network_mode: 'host'
    depends_on:
      - db

  db:
    image: postgres
    container_name: pg-survey
    restart: always
    env_file:    
      - .env     
    environment:
      - POSTGRES_DB=${DATABASE}   
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/postgres:/docker-entrypoint-initdb.d
